services:
  - type: web
    name: lai-vung-network
    runtime: python311
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: "3.13"
      - key: FORCE_REBUILD_V2
        value: "2026-05-25-tts-speak"
